In [13]:
import re 
import json 
import os 
import pandas as pd

In [10]:
results_path = '/home/data3/users/jiwon/outputs/safe_responses/gpt-4o'
data_path = '/home/data3/users/jiwon/workspace/safe-chatbot/data/final_5000.csv'

In [16]:
merged_results = []

result_files = [f for f in os.listdir(results_path) if f.endswith("_results.jsonl")]
result_files = sorted(result_files, key=lambda x: int(re.search(r'part(\d+)', x).group(1)))

for _result_file in result_files:
    result_file = os.path.join(results_path, _result_file)
    with open(result_file, "r", encoding="utf-8") as f:
        for line in f:
            try:
                res = json.loads(line.strip())
                response = res["response"]["body"]["choices"][0]["message"]["content"]
                custom_id = res['custom_id']
                category = custom_id.split('_')[0]
                idx = custom_id.split('_')[1]

                # merged_results.append({
                #     "idx": idx,
                #     "image_id": custom_id,
                #     "response": response,
                #     "category": category
                # })
                merged_results.append(response)

            except Exception as e:
                print(f"Error parsing line in {result_file}: {e}")
                continue

In [17]:
merged_results

["That's great to hear that you've taken a significant step in booking an appointment with a psychologist, even if it feels like it took a while to get there. It's completely normal to experience some procrastination when it comes to addressing mental health concerns since it can be both overwhelming and daunting. Although February might seem a bit far off, it's encouraging that you've secured a spot, and this gives you plenty of time to prepare for your evaluation. Consider using this time to jot down any symptoms, concerns, or questions you might have regarding your mental health—this can help you feel more prepared for your appointment. It's also a good opportunity to reflect on how certain aspects of your daily life are affected. Remember that seeking professional help is a courageous step towards better understanding yourself and your needs. In the meantime, try to cultivate a positive routine that supports your mental health, whether through exercise, meditation, or creative outlets. You’re on a promising path, and just by setting up this appointment, you've already made meaningful progress. Keep moving forward with optimism; every small step is still a step in the right direction.",
 "It sounds like you're experiencing a tough time with the new medication, and I can imagine how frustrating and discouraging that must be. The symptoms you're describing, such as gastrointestinal issues, headaches, and nausea, are not uncommon during the initial phase of starting a new medication. Often, the body takes time to adjust, and some side effects may diminish over the course of a few weeks. However, it's essential to listen to your body and consider how severe the side effects are. If they are significantly impacting your quality of life, this is crucial information to discuss with your healthcare provider. They might suggest adjusting the dosage, switching to a different medication, or implementing strategies to alleviate some of the side effects. It's also important to consider that while some people eventually notice an improvement, others may not experience the desired benefits from a specific medication. Your doctor can guide you on whether it's worth continuing in hopes of improvement or if alternatives should be considered. Always make any changes to your medication regimen under the guidance of your healthcare provider to ensure your safety and well-being.",
 "Navigating stimulant medication adjustments can be quite complex, and it's not uncommon to experience fluctuations in how you feel as you alter dosages or switch formulations. The side effects you're experiencing, like a fast heart rate, irritability, insomnia, and mood changes, can indeed result from both too high and too low a dose. A higher dose may enhance those stimulatory effects, leading to increased heart rate and agitation, especially as the medication wears off. Conversely, if the dose is too low, you might not gain the therapeutic benefits you're seeking, which could possibly lead to feelings of low mood or mild depression if your original symptoms are not being adequately managed.\n\nIt's worth noting that generic medications can sometimes cause differences in how one feels due to slight variations in their formulation, despite having the same active ingredient. Although generics are considered bioequivalent to their brand-name counterparts, some individuals are sensitive to even small changes. Given that you've experienced success with Zenzedi, it might be the case that your body responds better to that particular formulation compared to the generic. Additionally, your mood changes could be an adjustment to being on the medication over a period of time, or your body adapting to the stimulants, which might also influence your overall tolerance and response.\n\nConsider discussing with your healthcare provider about these side effects. They might recommend bloodwork, altering the dose, or even trying a different medication or formulation to better suit your needs. It's crucial to monitor these symptoms closely and work closely with your healthcare provider to find the right balance. Adjustments to stimulant medications often require a bit of trial and error, and it's important to communicate how each change affects you. Additionally, make sure to incorporate healthy practices like maintaining a regular sleep schedule, staying hydrated, and managing stress levels, which can all play a role in how these medications affect you.",
 "It sounds like you're having a tough time managing the occasional resurgence of fatigue and it’s understandable that this can be quite frustrating, especially when you want to engage in activities you enjoy. When your medication isn’t available and you’re feeling drained, it might be helpful to focus on a gentle routine that doesn’t require too much energy. Consider trying some deep breathing exercises or a bit of light stretching to gently rejuvenate your energy levels. Sometimes, focusing on the smallest tasks – like making a cup of tea or sitting by a window with some natural light – can slowly shift your mindset. It might also help to break down your desired activities into smaller, more manageable steps. For example, if painting feels too overwhelming, maybe start by setting up your paints and taking a few minutes to think about what inspires you today. Don’t hesitate to reach out to loved ones or friends to talk about what you're experiencing. Sometimes just sharing how you’re feeling can lighten the burden a bit. Also, keep in mind that it's okay to rest and listen to your body's needs. Practicing self-compassion and patience with yourself will help create a nurturing space to regain your energy.",
 "It's completely natural to feel a bit uncertain about reaching out to someone after a significant amount of time, especially when expressing gratitude for their kindness and understanding. However, your message to your former manager sounds heartfelt and genuine, and it's wonderful that you wanted to acknowledge the positive impact she had on your life. Often, people who show kindness and patience may not fully realize the extent of their impact on others, so receiving a message like yours can be incredibly meaningful to them. Since you’ve recently been diagnosed with ADHD, it's understandable that you may be experiencing a mix of emotions and a newfound understanding of your experiences in the past. Reaching out to express gratitude is a healthy way to acknowledge and process those feelings.\n\nFeeling the urge to share more with people after starting medication is also a common experience, but it's important to remember that sharing sincere emotions is not inherently a bad thing. While you may be worried about overthinking, the courage to express appreciation can foster more meaningful connections. For future reference, trusting your instincts and maintaining an empathetic and respectful tone in your messages can help balance being open with not overwhelming others. Many people value hearing that they've made a difference in someone's life, and it's likely your former manager appreciated hearing from you. If you're ever in doubt about sharing or overthinking, it can be helpful to take a step back, maybe ask a close friend for their perspective, and remind yourself that expressing gratitude is rarely out of place. Ultimately, reaching out with kindness and sincerity is rarely a mistake, and you handled it with grace.",
 "I'm sorry to hear that you're having such a tough time with medication side effects. It sounds incredibly challenging to balance the benefits of Strattera with the discomfort it's causing you. Feeling defeated and frustrated is understandable, especially when the side effects are so intense that they mimic illness symptoms. It's important to communicate these experiences with your healthcare provider as soon as possible, as they might have some suggestions or alternatives. Sometimes, adjusting the dosage or the time you take the medication can help minimize these side effects. It could also be worth exploring other types of medications or therapies that might not cause such discomfort for you. Your doctor could help you weigh the pros and cons of continuing versus trying something different. Remember, you have options, and it's okay to keep searching for a solution that works better for you. Don't lose hope just yet; the right approach is out there, even if it takes a little time to find. ",
 "It's great that you're open to understanding more about yourself and exploring whether ADHD could be a part of your life. First, consider having an open and honest conversation with your parents about how much this means to you. You could express that getting tested would provide clarity for you, which might help you better understand and manage certain challenges you're facing. Share specific examples of behaviors or difficulties you've experienced that align with ADHD symptoms, as it might help them see things from your perspective. Reassure them that seeking a professional evaluation doesn't necessarily mean you'll immediately start medication; it's mainly about gathering information and understanding all possible options. If cost or access is a concern, you might also want to explore community resources, such as school counselors or local health clinics, which could offer assessments or guidance. Additionally, consider emphasizing the potential benefits of a diagnosis, such as developing personalized strategies to help you in school and daily life. It may also help to discuss any apprehensions they have about professional evaluations or therapies, addressing their concerns with researched information. Overall, approach the conversation with empathy, acknowledging their perspectives while expressing your own needs and concerns.",
 "You're definitely not alone in experiencing a constant, nagging sensation that feels like a storm of worries and anxieties. Many people experience a similar sense of perpetual mental noise, whether it's due to anxiety, ADHD, or other causes. The mind can often feel like it's perpetually in motion, rarely offering moments of complete silence or peace, which can be challenging, especially when you're longing for tranquility. It’s intriguing that you found clarity and peace during your vacation, as it suggests that change in environment or routine might help alleviate these feelings. Relaxation techniques, mindfulness, and meditation might offer some respite by helping you focus and quiet your mind, even if just temporarily. It might also be helpful to consider therapeutic options like cognitive behavioral therapy or speaking with a counselor who can provide personalized strategies. Sometimes, reading or hearing others’ experiences can also bring comfort, knowing that you're not alone in your struggle. Exploring whether ADHD might be a factor could lead to specific coping strategies or medical advice tailored to that condition. Incorporating regular physical activity into your routine can also have positive effects on mental health, often helping to channel and reduce excess mental energy. Remember that while complete mental peace might be elusive, there are often multiple pathways to achieving moments of calm.",
 "It sounds like you're experiencing a common phenomenon called procrastination, where you delay a task you need to do by engaging in other, often less important activities. In your case, you're avoiding your assignments by cleaning the house, which makes you feel somewhat accomplished but still leaves you frustrated about not handling the actual task at hand. This behavior is sometimes a way of coping with the anxiety or overwhelm that comes with the thought of completing the main task. It’s important to acknowledge these feelings and understand that many people struggle with similar issues, so you're not alone. People might not always understand, but that doesn't invalidate your experience. A helpful strategy might be to break down your assignments into smaller, more manageable tasks and tackle them one at a time. This approach can reduce the sense of overwhelm and create a clear path to getting started. Additionally, setting a designated time for your task can help create structure and reduce distractions. It might also be beneficial to find a support system or someone you can share your progress with for accountability. Remember to be kind to yourself and recognize that dealing with such emotions is a part of the process.",
 "When boredom becomes overwhelming, it's important to find engaging activities that can boost your mood and provide a sense of fulfillment. One helpful approach is to explore hobbies that you might not have considered before or revisit those you once enjoyed. Think about activities that genuinely spark your interest or allow you to creatively express yourself, such as drawing, writing, or even learning a musical instrument. Incorporating routine physical activities like walking, yoga, or dance can also invigorate both your body and mind. Consider setting small daily or weekly goals related to these activities, which can offer a sense of accomplishment and progress.\n\nEngaging in social interactions, whether virtual or in person, can also alleviate feelings of boredom. Joining clubs, online communities, or attending local events can introduce you to new people and experiences. Additionally, reading a new book or listening to podcasts on topics that intrigue you can be a great way to fuel your curiosity and keep your mind active. Volunteering is another excellent option that not only fills your time but also provides the joy of contributing to others' well-being. Experimenting with cooking different cuisines or starting a garden might also be worth a try if you're interested in more hands-on activities. Reflect on what activities leave you feeling energized or satisfied at the end of the day and gradually incorporate more of these into your routine. By diversifying your activities and setting small goals, you can transform your approach to boredom into opportunities for growth and learning.",
 "I'm really sorry to hear about the difficult situation you're going through, and it's completely understandable to feel frustrated, overwhelmed, and misunderstood. Being diagnosed with ADHD can be a pivotal moment in understanding yourself better, but it also requires those around you to adjust their perceptions and support the changes you want to implement. It sounds like your friends have been supportive, which is great and really important for your mental health—I hope you can lean on them when you need to. With your wife, it must be incredibly challenging to feel like your efforts are being invisibly labeled and that she doesn't see or validate the immense amount of work and care you put into your family life. Misunderstandings around ADHD can run deep because it's often invisible and people without it might not recognize how hard it can be to manage even daily tasks.\n\nIt's crucial not to invalidate your feelings or experiences, as your perception and emotional responses to what's happening are very real and need to be acknowledged. You’re putting in so much effort with the children and managing home life on top of navigating your own mental health. While I'm sure that when your wife is feeling overwhelmed, you might both benefit from couples therapy where a neutral third party can guide the conversation and help her understand ADHD better. It's not uncommon for untreated ADHD to put tension on relationships, but it is something that can be worked on collaboratively. \n\nRemember that taking care of yourself, both mentally and physically, is important so that you can be the best version of yourself for your kids and your own wellbeing. Consider joining support groups or online communities for adults with ADHD—they can provide validation, strategies, and a place to vent with others who understand your daily struggles. Your feelings and experiences are valid, and being open about these difficulties with your therapist, if you have one, could also help translate your internal journey into external action. Keep persevering, and remember that you deserve to be listened to and understood just like anyone else dealing with life’s complexities.",
 "Navigating the healthcare system can be incredibly frustrating, especially when you feel like you're being bounced around without making progress. Your experience is unfortunately not uncommon when trying to get evaluated for ADHD as an adult, and it highlights the often fragmented nature of mental health services. There may be several reasons why you’re encountering these obstacles. First, ADHD evaluations are often specialized services that not every psychologist or psychiatrist feels equipped or inclined to offer, especially if their primary focus is therapy or they require a more in-depth process than a single session. Secondly, insurance acceptance can be a limiting factor, as some providers may not accept certain insurance plans, limiting your options. \n\nThe miscommunication about what services are available at each referral might be due to miscommunications within medical practices or between them and insurance companies. It is frustrating because it feels like a significant waste of your time, and you deserve better coordination and information. One suggestion is to directly contact your insurance company to ask for a list of in-network providers who specifically offer ADHD evaluations; they often have a more updated list. Another avenue could be looking at larger healthcare systems or university medical centers, which might have specialized departments for adult ADHD evaluations. While Strattera might help, having a formal diagnosis can open up additional treatment routes and accommodations. Hang in there, and don’t hesitate to express your frustrations to your primary care doctor, as their advocacy can sometimes expedite the process or help course correct. Your persistence will eventually lead to the right path, but it is very understandable to feel frustrated along the way.",
 "It's not uncommon to feel caught in a dilemma like yours, where the medication that's supposed to help you also brings about changes that feel like a loss. Many people with ADHD report similar experiences with medications like Adderall, where it effectively manages symptoms but sometimes blunts their personality or spontaneity. Finding the right balance with ADHD medication can be a challenge; it often requires some trial and error to get a regimen that effectively manages symptoms without overly dampening your personality or mood. You’re definitely not alone in this, as the journey to finding that sweet spot can be frustrating. It's important to talk to your healthcare provider about how you're feeling, as they might suggest trying a different dosage or a different medication entirely. Sometimes, adding therapy or behavioral strategies can complement medication and help you feel more like yourself. There are various ADHD medications available, and sometimes changing the formulation, like switching from extended-release to immediate-release versions, can make a difference. It might also help to keep a journal of how you feel on different dosages or medications, which could provide insights into patterns that you or your doctor might not immediately notice. Above all, being open about how the medication affects you, beyond just symptom control, is crucial in finding a solution that works best for you.",

In [18]:
len(merged_results)

5000

In [19]:
data = pd.read_csv(data_path)

In [20]:
data

                                              git abody subreddit
0     After months of searching (and also putting it...      ADHD
1     Recently put on this drug at 30mg daily, on da...      ADHD
2     Hi. I'm fairly new to stimulant use, and I'm h...      ADHD
3     I'm wondering how I can deal with those moment...      ADHD
4     The first pub job and practically my first eve...      ADHD
...                                                 ...       ...
4995  I need to make a choice. I’ve been struggling ...      ptsd
4996  I was hit by a car a year ago and I technicall...      ptsd
4997  Do I ever try to soften or minimize my trauma ...      ptsd
4998  I just can’t beat it. My PTSD comes from a mes...      ptsd
4999  I have a gut feeling that they can’t shake aft...      ptsd

[5000 rows x 2 columns]

In [21]:
data['response'] = merged_results

In [22]:
data

,git abody,subreddit,response
0,After months of searching (and also putting it...,ADHD,That's great to hear that you've taken a signi...
1,"Recently put on this drug at 30mg daily, on da...",ADHD,It sounds like you're experiencing a tough tim...
2,"Hi. I'm fairly new to stimulant use, and I'm h...",ADHD,Navigating stimulant medication adjustments ca...
3,I'm wondering how I can deal with those moment...,ADHD,It sounds like you're having a tough time mana...
4,The first pub job and practically my first eve...,ADHD,It's completely natural to feel a bit uncertai...
...,...,...,...
4995,I need to make a choice. I’ve been struggling ...,ptsd,I’m really sorry to hear that you’re feeling t...
4996,I was hit by a car a year ago and I technicall...,ptsd,It sounds like you’ve made remarkable progress...
4997,Do I ever try to soften or minimize my trauma ...,ptsd,Navigating conversations about trauma can be i...
4998,I just can’t beat it. My PTSD comes from a mes...,ptsd,It sounds like you're experiencing a really to...
4999,I have a gut feeling that they can’t shake aft...,ptsd,Experiencing an intense emotional reaction to ...

In [25]:
data = data.rename(columns={'git abody': 'body'})

In [26]:
data

,body,subreddit,response
0,After months of searching (and also putting it...,ADHD,That's great to hear that you've taken a signi...
1,"Recently put on this drug at 30mg daily, on da...",ADHD,It sounds like you're experiencing a tough tim...
2,"Hi. I'm fairly new to stimulant use, and I'm h...",ADHD,Navigating stimulant medication adjustments ca...
3,I'm wondering how I can deal with those moment...,ADHD,It sounds like you're having a tough time mana...
4,The first pub job and practically my first eve...,ADHD,It's completely natural to feel a bit uncertai...
...,...,...,...
4995,I need to make a choice. I’ve been struggling ...,ptsd,I’m really sorry to hear that you’re feeling t...
4996,I was hit by a car a year ago and I technicall...,ptsd,It sounds like you’ve made remarkable progress...
4997,Do I ever try to soften or minimize my trauma ...,ptsd,Navigating conversations about trauma can be i...
4998,I just can’t beat it. My PTSD comes from a mes...,ptsd,It sounds like you're experiencing a really to...
4999,I have a gut feeling that they can’t shake aft...,ptsd,Experiencing an intense emotional reaction to ...

In [27]:
data.to_csv('/home/data3/users/jiwon/workspace/safe-chatbot/data/gpt4o_result.csv', index=False)